<?php
/**
 * Implements hook_preprocess_paragraph().
 */

 function feature_component_theme($existing, $type, $theme, $path) {
    return [
      'page--feature' => [
        'variables' => [ 
          'node' => NULL,
          'paragraphs' => [],
        ],
        'template' => 'page--feature',
      ],
    ];
  }

function feature_component_page_attachments_alter(array &$attachments)
{
  $route_uri = \Drupal::request()->getRequestUri();

  if(str_starts_with($route_uri, '/feature_component/')) {
    $attachments['#attached']['library'][] = 'feature_component/feature_style';
  }
}